name: check libevent and transmission versions
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  LIBEVENT_VERSION: "2.1.12-stable"
  TBT_VERSION: "3.00"

jobs:
  check-lib_event_version:
    runs-on: ubuntu-latest
    steps:
      - name: get libevent's latest version
        id: getlatestversion
        run: |
          ver=$(curl -s "https://api.github.com/repos/libevent/libevent/releases/latest" | jq -r .tag_name )
          echo "libevent build version: ${{ env.LIBEVENT_VERSION }}, latest github libevent version: ${ver}"
          if [[ ${{ env.LIBEVENT_VERSION }} != ${ver#*-} ]]; then exit 1; fi

  check-transmission_version:
      runs-on: ubuntu-latest
      steps:
        - name: get transmission's latest version
          id: getlatestversion
          run: |
            ver=$(curl -s "https://api.github.com/repos/transmission/transmission/releases/latest" | jq -r .tag_name )
            echo "transmission build version: ${{ env.TBT_VERSION }}, latest github transmission version: ${ver}"
            if [[ ${{ env.TBT_VERSION }} != ${ver} ]]; then exit 1; fi