# This is a basic workflow to help you get started with Actions

name: clean workflows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - tbt_v3
  pull_request:
    branches:
      - master
      - tbt_v3
  schedule:
      - cron: "0 6 * * *"
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clean:
    strategy:
      matrix:
        branch:
          - master
          - tbt_v3
          - dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DRY: false
    steps:
      - name: Delete failed workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_conclusions: |
            action_required
            cancelled
            failure
            neutral
            skipped
            stale
            timed_out
          save_period: 0
          save_min_runs_number: 0
          branch: ${{ matrix.branch }}
          dry: ${{ env.DRY }}

      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 30
          save_min_runs_number: 5
          branch: ${{ matrix.branch }}
          dry: ${{ env.DRY }}