name: Image Builds with template workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .circleci/*
      #- .github/**
      - .gitignore
      - .dockerignore

jobs:
  build-transmission-v4:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      image-name: transmission-openvpn
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: 4
      version: 4
      tag: "tbt_v4"
    secrets: inherit

  build-transmission-v3:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      image-name: transmission-openvpn
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: latest
      version: 3
      tag: latest
    secrets: inherit