name: Image Builds with template workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - README.md
      - docker-compose.yml
      - mkdocs.yml
      - .github/**
      - docs/*
      - images/*
      - upstream/Dockerfile
      - upstream/transmission-sha.txt
      - upstream/transmission-version.txt
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-transmission-v4-dev:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: dev
      version: 4
      tags: edgd1er/transmission-openvpn:dev
    secrets: inherit

  build-transmission-v4:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: 4.0.5
      version: 4
      tags: edgd1er/transmission-openvpn:latest,edgd1er/transmission-openvpn:tbt_v4
    secrets: inherit

  build-transmission-v3:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: 3.00
      version: 3
      tags: edgd1er/transmission-openvpn:tbt_v3
    secrets: inherit