name: Image Builds with template workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - .github/**
      - .gitignore
      - .dockerignore

jobs:
  build-transmission-v4-dev:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: dev
      version: 4
      tags: edgd1er/transmission-openvpn:dev
    secrets: inherit

  build-transmission-v4:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: 4.0.4
      version: 4
      tags: edgd1er/transmission-openvpn:latest,edgd1er/transmission-openvpn:tbt_v4
    secrets: inherit

  build-transmission-v3:
    uses: ./.github/workflows/image-build-template-workflow.yml
    with:
      build-context: '.'
      event_version: "2.1.12-stable"
      tbt_version: 3.00
      version: 3
      tags: edgd1er/transmission-openvpn:tbt_v3
    secrets: inherit