name: Reusable workflow

on:
  workflow_call:
    inputs:
      event_version:
        type: string
        default: "2.1.12-stable"
      tbt_version:
        required: false
        type: string
        default: "4.0.6"
      build-context:
        required: true
        type: string
      version:
        required: true
        type: string
      tags:
        required: true
        type: string

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm, linux/arm64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # QEMU emulator to build for other platforms
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      # Buildx automates creating the multi-arch manifest build
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          install: true
          use: true

      # Display instances
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Cache Docker layers
        if: false
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # show available plateforms
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Authenticate so that we can push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ inputs.build-context }}
          file: ./Dockerfile
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow}}
          # removed linux/arm64
          platforms: ${{ matrix.plateform }}
          push: true
          build-args: |
            REVISION=${{ github.sha }}
            LIBEVENT_VERSION=${{ inputs.event_version }}
            TBT_VERSION=${{ inputs.version }}
          tags: ${{ inputs.tags }}
      - name: gettag
        uses: jungwinter/split@v2
        id: split
        with:
            msg: ${{ inputs.tags }}
            separator: ','
      - name: set_print
        id: gettag
        run: |
          echo "split_1:  ${{ steps.split.outputs._1 }}"
          docker buildx imagetools inspect  ${{ steps.split.outputs._0 }}
      # inspect vulnerabilities
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ steps.split.outputs._0 }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'